### ISSUE TITLE
Up Tilt: Adjust cancel frames

### ISSUE THREAD

**Issue by ZeDespo** [ZeDespo/Ultimate-Ganondorf#7]
Up tilt is way too spammable on its own. If Up tilt misses, Ganondorf should go through the entire animation before being able to act. If Ganondorf hits someone with up tilt, he should be able to act out of it in the way he can currently.

**Comment by FatherOfEgg** [comment]
Is there a specific frame/hitbox he must hit the opponent with in order to act out of it? For example, IFF he hit the opponent on [frame 8](https://github.com/ZeDespo/Ultimate-Ganondorf/blob/5de5dd1f62b3981e3b6a54ffe96d0d8fe768918d/src/ganon/acmd/ground/attack_up_tilt.rs#L80). Or do you want it so that no matter what, as long as he hits someone (could be the very last frame of the last hitbox), he gets to act out of it?

**Comment by ZeDespo** [comment]
I haven't really thought about that. What do you think? Me personally, I thought that if any hitbox hits, it should then be made cancellable; however, Since we know where the opponent is going to end up at the end of the up tilt, we could always introduce that if and only if logic on the same frame as the last hitbox.

**Comment by FatherOfEgg** [comment]
Makes sense. For now we'll make it so that if any hitbox hits, at any frame, he can act out of it. We can always change it later.

**Comment by FatherOfEgg** [comment]
Just to confirm, whenever he hits someone, he is allowed to act out at [frame 26](https://github.com/ZeDespo/Ultimate-Ganondorf/blob/5de5dd1f62b3981e3b6a54ffe96d0d8fe768918d/src/ganon/acmd/ground/attack_up_tilt.rs#L144) (Which is what he is currently doing). Or, when he hits someone, he is immediately able to act?

**Comment by ZeDespo** [comment]
Yes, the current implementation should be the cancel behavior. So on frame 26, he could cancel into anything
